# Generated by Django 2.0.6 on 2019-02-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='eventID',
        ),
        migrations.AlterField(
            model_name='event',
            name='eventname',
            field=models.CharField(db_index=True, max_length=30, primary_key=True, serialize=False),
        ),
    ]
